from tkinter import *
window=Tk()
window.title("Student Record Application")
window.geometry("400x250")
l1=Label(text="Name").grid(row=0,column=0)
l2=Label(text="Major").grid(row=1,column=0)
l3=Label(text="Sex").grid(row=2,column=0)
l4=Label(text="GPA").grid(row=3,column=0)
e1=Entry(window,width=20).grid(row=0,column=1)
e2=Entry(window,width=20).grid(row=1,column=1)
e3=Entry(window,width=20).grid(row=2,column=1)
e4=Entry(window,width=20).grid(row=3,column=1)
l5=Label(text="ID").grid(row=0,column=2)
l6=Label(text="Age").grid(row=1,column=2)
l7=Label(text="Address").grid(row=2,column=2)
e5=Entry(window,width=20).grid(row=0,column=3)
e6=Entry(window,width=20).grid(row=1,column=3)
e7=Entry(window,width=20).grid(row=2,column=3)
b1=Button(window,text="View All",width=12).grid(row=4,column=3)
b2=Button(window,text="Search Entry",width=12).grid(row=5,column=3)
b3=Button(window,text="Add Entry",width=12).grid(row=6,column=3)
b4=Button(window,text="Update Selected",width=12).grid(row=7,column=3)
b5=Button(window,text="Delete Selected",width=12).grid(row=8,column=3)
b6=Button(window,text="Close",width=12).grid(row=9,column=3)
window.mainloop()